### ISSUE TITLE
[TODO] Road to 4.2

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc21_cookie-manager#14]
#### Backend
- [x] Correct the "SameSite" option for the manager cookies ([see](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) + Browser console)
- [x] Clean up category selection (Uncategorized) and put in a real "Uncategorized" during the Joomla! installation
- [x] #15 assigned to @shazmasiddiqui
![grafik](https://user-images.githubusercontent.com/1229869/166439217-562717b2-416c-4910-9881-645c04ce8c7e.png)
- [x] #16 assigned to @shazmasiddiqui
- [x] #17 assigned to @shazmasiddiqui
- [x] #19 assigned to @shazmasiddiqui
![grafik](https://user-images.githubusercontent.com/1229869/166442465-45373877-c82f-4b33-8eef-cc2fd5fc69ca.png)
![grafik](https://user-images.githubusercontent.com/1229869/166442870-f85b03bb-2ca1-42e1-93a1-503162fa9ea0.png)
- [x] Show the category name instead of the category ID in the cookie list assigned to @shazmasiddiqui
![image](https://user-images.githubusercontent.com/359377/171925874-37d8aea8-d327-415a-9985-af5e1d4b32ca.png)

#### Frontend
- [x]  Don't load Cookie Manager in the frontend, when no cookies are defined assigned to @shazmasiddiqui
- [x] Only show categories with cookies attached in the consens banner/settings modal assigned to @shazmasiddiqui
- [x] Move consens banner code to the beginning of the page (after the ```<body>``` tag)
- [ ] Check with @chmst if the cookie banner (+ the switch to the settings view) is accessible
- [ ] #51
- [ ] After applying a consens the site should refresh

### Code improvements
- [ ] Replace all "Factory"-calls with calls from the DI container
- [x] #28

### New features
- [ ] Implement a "registerCookie" service
- [x] #22 assigned to @vorayash
- [x] Add a category option to set a category as mandatory (active by default and not de-selectable)
- [ ] Implement a scheduler plugin to delete outdated rows (based on the option "Consent Expiration Period")

### Documentation
- [ ] Fix the help link
- [ ] Write the documentation

### Extras
- [ ] Implement a small list of pre-defined cookies to use
- [ ] Automated cookie scanner

**Comment by brianteeman** [comment]
### Additional Todo Items
- [x] Move cookiemanager to a section in the Users Menu
- [x] Add cookiemanager to the alternative menu presets
- [ ] Language strings to follow style guide
- [x] Do not display cookie settings link in modals. (it gives an error as well)
- [ ] Do not use bootstrap in the frontend
- [ ] If bootstrap is being used (I hope it isnt) then use the web asset manager
- [ ] What is the purpose of the alias fieldview
- [ ] cookie manager category menu collapses the sidebar when closing a category
- [x] js error in the front end (uncaught type errj4or)
- [ ] policy link is not language aware
- [x] no list views support the new display columns options
- [x] save in a named category fails with same alias error message
- [x] scripts list view should have filters for position and type
- [ ] i have no idea what the scripts section is for and why the types are for thinks like images
- [ ] what is the point in storing expired consents?
- [ ] there should be a delete all expired consent button
- [ ] shouldnt cookies & scripts be managed in the same way as plugins. ie enabled/disabled and delete. no archive or trash
- [ ] does a cookie manager not need to let a user remove consent?
- [ ] cookie description etc is not language aware
- [x] help button links are using the old method
- [x] N_ITEMS_ strings are wrong. They should use %d not %s and we should have different for singular and plural. currently there is only plural
- [x] N_ITEMS_ strings should be changed to be more specific eg N_COOKIES_, N_SCRIPTS_ N_CONSENTS_
- [ ] Multiple accessibility errors in the front end
- [ ] consider adding columns in the consents table to show if they are in/out and add filters
